POST http://localhost:3001/products
content-Type: application/json

//register a new product!
{
    "name":"iPhone",
    "price": 5000
}
### fetch all

GET http://localhost:3001/products

### fetch by id
GET http://localhost:3001/products/c6df1db3-aa01-4a35-99b4-b5beb494149c


### fetch update
PUT http://localhost:3001/products/c6df1db3-aa01-4a35-99b4-b5beb494149c
content-Type: application/json

{
    "name":"iPhone 12",
    "price": 6.852
}

###
DELETE http://localhost:3001/products/4bfc7e4e-5295-406c-9a91-a156f539a4f5