import type { Metadata } from 'next'
import Link from 'next/link'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App - e.g by gmapdev',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <h1>
          Hello from <code>/app/layout.tsx</code>
        </h1>
        <header>
          <Link href="/">Home</Link>
          <Link href="http://localhost:3000/posts">Posts</Link>
          <Link href="/about">About</Link>
          <a
            href="https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts#with-typescript"
            target="_blank">
            Layout TypeScript
          </a>
        </header>
        {children}
      </body>
    </html>
  )
}
