import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-slate-500">
      <body>
        <h1 className="bg-red-600 p-3 font-bold text-center">Navegação</h1>
        {children}
      </body>
    </html>
  )
}
