import type { Metadata, ResolvingMetadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <nav className="bg-blue-500">
        <ul>
          <li>Perfil</li>
          <li>Conta</li>
        </ul>
      </nav>
      {children}
    </>
  )
}
